width = 2650
height = 1440

line_width = 1.0
line_scale_z = 0.2
line_scale_y = 50.0

line_offset_x_0 = -0.98
line_offset_y_0 = -0.90

line_offset_x_1 = -0.98
line_offset_y_1 = -0.7

xy_mult = 600.0
xy_rad = 3.0

grid_offset_x = 50.0
grid_offset_y = 70.0

grid_widget_scale = 1.5
